# Generated by Django 5.1.3 on 2024-11-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalidadAire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=100)),
                ('ica', models.FloatField()),
                ('proximidad', models.FloatField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
